//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlexRequests.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MockApiData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockApiData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlexRequests.Api.MockApiData", typeof(MockApiData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;title&quot;: &quot;Archer (2009)&quot;,
        ///    &quot;seasons&quot;: [
        ///      {
        ///        &quot;seasonNumber&quot;: 5,
        ///        &quot;monitored&quot;: true
        ///      },
        ///      {
        ///        &quot;seasonNumber&quot;: 4,
        ///        &quot;monitored&quot;: true
        ///      },
        ///      {
        ///        &quot;seasonNumber&quot;: 3,
        ///        &quot;monitored&quot;: true
        ///      },
        ///      {
        ///        &quot;seasonNumber&quot;: 2,
        ///        &quot;monitored&quot;: true
        ///      },
        ///      {
        ///        &quot;seasonNumber&quot;: 1,
        ///        &quot;monitored&quot;: true
        ///      },
        ///      {
        ///        &quot;seasonNumber&quot;: 0,
        ///        &quot;monitored&quot;: false
        ///      }
        ///    ],
        ///    &quot;pat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sonarr_AddSeriesResult {
            get {
                return ResourceManager.GetString("Sonarr_AddSeriesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;SD&quot;,
        ///    &quot;cutoff&quot;: {
        ///      &quot;id&quot;: 1,
        ///      &quot;name&quot;: &quot;SDTV&quot;
        ///    },
        ///    &quot;items&quot;: [
        ///      {
        ///        &quot;quality&quot;: {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;SDTV&quot;
        ///        },
        ///        &quot;allowed&quot;: true
        ///      },
        ///      {
        ///        &quot;quality&quot;: {
        ///          &quot;id&quot;: 8,
        ///          &quot;name&quot;: &quot;WEBDL-480p&quot;
        ///        },
        ///        &quot;allowed&quot;: true
        ///      },
        ///      {
        ///        &quot;quality&quot;: {
        ///          &quot;id&quot;: 2,
        ///          &quot;name&quot;: &quot;DVD&quot;
        ///        },
        ///        &quot;allowed&quot;: true
        ///      },
        ///      {
        ///        &quot;quality&quot;: { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sonarr_Profiles {
            get {
                return ResourceManager.GetString("Sonarr_Profiles", resourceCulture);
            }
        }
    }
}
