automation:
  - changed-files:
      - any-glob-to-any-file: 'tests/**/*'

frontend:
  - changed-files:
      - any-glob-to-any-file: 'src/Ombi/ClientApp/**/*'

backend:
  - changed-files:
      - any-glob-to-any-file: 'src/**/*.cs'

devops:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/*'
