//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlexRequests.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlexRequests.UI.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string Javascript_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Javascript_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Javascript_Success {
            get {
                return ResourceManager.GetString("Javascript_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Layout_Admin {
            get {
                return ResourceManager.GetString("Layout_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Layout_ChangePassword {
            get {
                return ResourceManager.GetString("Layout_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string Layout_Danish {
            get {
                return ResourceManager.GetString("Layout_Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Layout_Donate {
            get {
                return ResourceManager.GetString("Layout_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Layout_Dutch {
            get {
                return ResourceManager.GetString("Layout_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Layout_English {
            get {
                return ResourceManager.GetString("Layout_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Layout_German {
            get {
                return ResourceManager.GetString("Layout_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string Layout_Issues {
            get {
                return ResourceManager.GetString("Layout_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Layout_Italian {
            get {
                return ResourceManager.GetString("Layout_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Layout_Logout {
            get {
                return ResourceManager.GetString("Layout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Layout_Portuguese {
            get {
                return ResourceManager.GetString("Layout_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Layout_Requests {
            get {
                return ResourceManager.GetString("Layout_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Layout_Search {
            get {
                return ResourceManager.GetString("Layout_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Layout_Settings {
            get {
                return ResourceManager.GetString("Layout_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Layout_Spanish {
            get {
                return ResourceManager.GetString("Layout_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Layout_Swedish {
            get {
                return ResourceManager.GetString("Layout_Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plex Requests.
        /// </summary>
        public static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update available! Click.
        /// </summary>
        public static string Layout_UpdateAvailablePart1 {
            get {
                return ResourceManager.GetString("Layout_UpdateAvailablePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here!.
        /// </summary>
        public static string Layout_UpdateAvailablePart2 {
            get {
                return ResourceManager.GetString("Layout_UpdateAvailablePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to watch a movie or tv show but it&apos;s not currently on Plex?
        ///            Login below with your Plex.tv username and password!.
        /// </summary>
        public static string UserLogin_Paragraph {
            get {
                return ResourceManager.GetString("UserLogin_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login details are only used to authenticate your Plex account..
        /// </summary>
        public static string UserLogin_Paragraph_SpanHover {
            get {
                return ResourceManager.GetString("UserLogin_Paragraph_SpanHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserLogin_Password {
            get {
                return ResourceManager.GetString("UserLogin_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string UserLogin_SignIn {
            get {
                return ResourceManager.GetString("UserLogin_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UserLogin_Title {
            get {
                return ResourceManager.GetString("UserLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plex.tv Username .
        /// </summary>
        public static string UserLogin_Username {
            get {
                return ResourceManager.GetString("UserLogin_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserLogin_Username_Placeholder {
            get {
                return ResourceManager.GetString("UserLogin_Username_Placeholder", resourceCulture);
            }
        }
    }
}
