//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlexRequests.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlexRequests.UI.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Issues_Modal_Save {
            get {
                return ResourceManager.GetString("Issues_Modal_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an issue.
        /// </summary>
        public static string Issues_Modal_Title {
            get {
                return ResourceManager.GetString("Issues_Modal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subtitles.
        /// </summary>
        public static string Issues_NoSubs {
            get {
                return ResourceManager.GetString("Issues_NoSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Issues_Other {
            get {
                return ResourceManager.GetString("Issues_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Issues.
        /// </summary>
        public static string Issues_Playback {
            get {
                return ResourceManager.GetString("Issues_Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Audio.
        /// </summary>
        public static string Issues_WrongAudio {
            get {
                return ResourceManager.GetString("Issues_WrongAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Content.
        /// </summary>
        public static string Issues_WrongContent {
            get {
                return ResourceManager.GetString("Issues_WrongContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string Javascript_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Javascript_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Javascript_Success {
            get {
                return ResourceManager.GetString("Javascript_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Layout_Admin {
            get {
                return ResourceManager.GetString("Layout_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Layout_ChangePassword {
            get {
                return ResourceManager.GetString("Layout_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string Layout_Danish {
            get {
                return ResourceManager.GetString("Layout_Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Layout_Donate {
            get {
                return ResourceManager.GetString("Layout_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Layout_Dutch {
            get {
                return ResourceManager.GetString("Layout_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Layout_English {
            get {
                return ResourceManager.GetString("Layout_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Layout_German {
            get {
                return ResourceManager.GetString("Layout_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string Layout_Issues {
            get {
                return ResourceManager.GetString("Layout_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Layout_Italian {
            get {
                return ResourceManager.GetString("Layout_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Layout_Logout {
            get {
                return ResourceManager.GetString("Layout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Layout_Portuguese {
            get {
                return ResourceManager.GetString("Layout_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Layout_Requests {
            get {
                return ResourceManager.GetString("Layout_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Layout_Search {
            get {
                return ResourceManager.GetString("Layout_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Layout_Settings {
            get {
                return ResourceManager.GetString("Layout_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Layout_Spanish {
            get {
                return ResourceManager.GetString("Layout_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Layout_Swedish {
            get {
                return ResourceManager.GetString("Layout_Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plex Requests.
        /// </summary>
        public static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update available! Click.
        /// </summary>
        public static string Layout_UpdateAvailablePart1 {
            get {
                return ResourceManager.GetString("Layout_UpdateAvailablePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here!.
        /// </summary>
        public static string Layout_UpdateAvailablePart2 {
            get {
                return ResourceManager.GetString("Layout_UpdateAvailablePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Layout_Welcome {
            get {
                return ResourceManager.GetString("Layout_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Search_Albums {
            get {
                return ResourceManager.GetString("Search_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Seasons.
        /// </summary>
        public static string Search_AllSeasons {
            get {
                return ResourceManager.GetString("Search_AllSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Search_Available {
            get {
                return ResourceManager.GetString("Search_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string Search_ComingSoon {
            get {
                return ResourceManager.GetString("Search_ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Search_Country {
            get {
                return ResourceManager.GetString("Search_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Season.
        /// </summary>
        public static string Search_FirstSeason {
            get {
                return ResourceManager.GetString("Search_FirstSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Theaters.
        /// </summary>
        public static string Search_InTheaters {
            get {
                return ResourceManager.GetString("Search_InTheaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Season.
        /// </summary>
        public static string Search_LatestSeason {
            get {
                return ResourceManager.GetString("Search_LatestSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string Search_Modal_SeasonsTitle {
            get {
                return ResourceManager.GetString("Search_Modal_SeasonsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Search_Movies {
            get {
                return ResourceManager.GetString("Search_Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to watch something that is not currently on Plex?! No problem! Just search for it below and request it!.
        /// </summary>
        public static string Search_Paragraph {
            get {
                return ResourceManager.GetString("Search_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string Search_ReportIssue {
            get {
                return ResourceManager.GetString("Search_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Search_Request {
            get {
                return ResourceManager.GetString("Search_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        public static string Search_Requested {
            get {
                return ResourceManager.GetString("Search_Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Search_Season {
            get {
                return ResourceManager.GetString("Search_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .
        /// </summary>
        public static string Search_SelectSeason {
            get {
                return ResourceManager.GetString("Search_SelectSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me a notification when items I have requested have been added.
        /// </summary>
        public static string Search_SendNotificationText {
            get {
                return ResourceManager.GetString("Search_SendNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string Search_Suggestions {
            get {
                return ResourceManager.GetString("Search_Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Count.
        /// </summary>
        public static string Search_TrackCount {
            get {
                return ResourceManager.GetString("Search_TrackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string Search_TvShows {
            get {
                return ResourceManager.GetString("Search_TvShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to watch a movie or tv show but it&apos;s not currently on Plex?
        ///            Login below with your Plex.tv username and password!.
        /// </summary>
        public static string UserLogin_Paragraph {
            get {
                return ResourceManager.GetString("UserLogin_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login details are only used to authenticate your Plex account..
        /// </summary>
        public static string UserLogin_Paragraph_SpanHover {
            get {
                return ResourceManager.GetString("UserLogin_Paragraph_SpanHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserLogin_Password {
            get {
                return ResourceManager.GetString("UserLogin_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string UserLogin_SignIn {
            get {
                return ResourceManager.GetString("UserLogin_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UserLogin_Title {
            get {
                return ResourceManager.GetString("UserLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plex.tv Username .
        /// </summary>
        public static string UserLogin_Username {
            get {
                return ResourceManager.GetString("UserLogin_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserLogin_Username_Placeholder {
            get {
                return ResourceManager.GetString("UserLogin_Username_Placeholder", resourceCulture);
            }
        }
    }
}
