//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlexRequests.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlexRequests.UI.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Common_Approve {
            get {
                return ResourceManager.GetString("Common_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Common_Approved {
            get {
                return ResourceManager.GetString("Common_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save, please try again.
        /// </summary>
        public static string Common_CouldNotSave {
            get {
                return ResourceManager.GetString("Common_CouldNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Common_Remove {
            get {
                return ResourceManager.GetString("Common_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate to Library Maintainer.
        /// </summary>
        public static string Custom_Donation_Default {
            get {
                return ResourceManager.GetString("Custom_Donation_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string Issues_Issue {
            get {
                return ResourceManager.GetString("Issues_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Issues_Modal_Save {
            get {
                return ResourceManager.GetString("Issues_Modal_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an issue.
        /// </summary>
        public static string Issues_Modal_Title {
            get {
                return ResourceManager.GetString("Issues_Modal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subtitles.
        /// </summary>
        public static string Issues_NoSubs {
            get {
                return ResourceManager.GetString("Issues_NoSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Issues_Other {
            get {
                return ResourceManager.GetString("Issues_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Issues.
        /// </summary>
        public static string Issues_Playback {
            get {
                return ResourceManager.GetString("Issues_Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Audio.
        /// </summary>
        public static string Issues_WrongAudio {
            get {
                return ResourceManager.GetString("Issues_WrongAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Content.
        /// </summary>
        public static string Issues_WrongContent {
            get {
                return ResourceManager.GetString("Issues_WrongContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string Javascript_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Javascript_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Javascript_Success {
            get {
                return ResourceManager.GetString("Javascript_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Layout_Admin {
            get {
                return ResourceManager.GetString("Layout_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently we are indexing all of the available tv shows and movies on the Plex server, so there might be some unexpected behavior. This shouldn&apos;t take too long..
        /// </summary>
        public static string Layout_CacherRunning {
            get {
                return ResourceManager.GetString("Layout_CacherRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Layout_ChangePassword {
            get {
                return ResourceManager.GetString("Layout_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string Layout_Danish {
            get {
                return ResourceManager.GetString("Layout_Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Layout_Donate {
            get {
                return ResourceManager.GetString("Layout_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Layout_Dutch {
            get {
                return ResourceManager.GetString("Layout_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Layout_English {
            get {
                return ResourceManager.GetString("Layout_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Layout_French {
            get {
                return ResourceManager.GetString("Layout_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Layout_German {
            get {
                return ResourceManager.GetString("Layout_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string Layout_Issues {
            get {
                return ResourceManager.GetString("Layout_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Layout_Italian {
            get {
                return ResourceManager.GetString("Layout_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Layout_Logout {
            get {
                return ResourceManager.GetString("Layout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Layout_Portuguese {
            get {
                return ResourceManager.GetString("Layout_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Layout_Requests {
            get {
                return ResourceManager.GetString("Layout_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Layout_Search {
            get {
                return ResourceManager.GetString("Layout_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Layout_Settings {
            get {
                return ResourceManager.GetString("Layout_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Layout_Spanish {
            get {
                return ResourceManager.GetString("Layout_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Layout_Swedish {
            get {
                return ResourceManager.GetString("Layout_Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plex Requests.
        /// </summary>
        public static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update available! Click.
        /// </summary>
        public static string Layout_UpdateAvailablePart1 {
            get {
                return ResourceManager.GetString("Layout_UpdateAvailablePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here!.
        /// </summary>
        public static string Layout_UpdateAvailablePart2 {
            get {
                return ResourceManager.GetString("Layout_UpdateAvailablePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string Layout_Usermanagement {
            get {
                return ResourceManager.GetString("Layout_Usermanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Layout_Welcome {
            get {
                return ResourceManager.GetString("Layout_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Requests_AlbumsTabTitle {
            get {
                return ResourceManager.GetString("Requests_AlbumsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Movies.
        /// </summary>
        public static string Requests_ApproveMovies {
            get {
                return ResourceManager.GetString("Requests_ApproveMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Music.
        /// </summary>
        public static string Requests_ApproveMusic {
            get {
                return ResourceManager.GetString("Requests_ApproveMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve TV Shows.
        /// </summary>
        public static string Requests_ApproveTvShows {
            get {
                return ResourceManager.GetString("Requests_ApproveTvShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Requests_Available {
            get {
                return ResourceManager.GetString("Requests_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Movies.
        /// </summary>
        public static string Requests_DeleteMovies {
            get {
                return ResourceManager.GetString("Requests_DeleteMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Music.
        /// </summary>
        public static string Requests_DeleteMusic {
            get {
                return ResourceManager.GetString("Requests_DeleteMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete TV Shows.
        /// </summary>
        public static string Requests_DeleteTVShows {
            get {
                return ResourceManager.GetString("Requests_DeleteTVShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Requests_Filter {
            get {
                return ResourceManager.GetString("Requests_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Requests_Filter_All {
            get {
                return ResourceManager.GetString("Requests_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Requests_Filter_Approved {
            get {
                return ResourceManager.GetString("Requests_Filter_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Requests_Filter_Available {
            get {
                return ResourceManager.GetString("Requests_Filter_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Approved.
        /// </summary>
        public static string Requests_Filter_NotApproved {
            get {
                return ResourceManager.GetString("Requests_Filter_NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string Requests_Filter_NotAvailable {
            get {
                return ResourceManager.GetString("Requests_Filter_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Released.
        /// </summary>
        public static string Requests_Filter_NotReleased {
            get {
                return ResourceManager.GetString("Requests_Filter_NotReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        public static string Requests_Filter_Released {
            get {
                return ResourceManager.GetString("Requests_Filter_Released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Available.
        /// </summary>
        public static string Requests_MarkAvailable {
            get {
                return ResourceManager.GetString("Requests_MarkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Unavailable.
        /// </summary>
        public static string Requests_MarkUnavailable {
            get {
                return ResourceManager.GetString("Requests_MarkUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Requests_MoviesTabTitle {
            get {
                return ResourceManager.GetString("Requests_MoviesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Requests_Order {
            get {
                return ResourceManager.GetString("Requests_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Releases.
        /// </summary>
        public static string Requests_Order_LatestReleases {
            get {
                return ResourceManager.GetString("Requests_Order_LatestReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Requests.
        /// </summary>
        public static string Requests_Order_LatestRequests {
            get {
                return ResourceManager.GetString("Requests_Order_LatestRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest Releases.
        /// </summary>
        public static string Requests_Order_OldestReleases {
            get {
                return ResourceManager.GetString("Requests_Order_OldestReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest Requests.
        /// </summary>
        public static string Requests_Order_OldestRequests {
            get {
                return ResourceManager.GetString("Requests_Order_OldestRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below you can see yours and all other requests, as well as their download and approval status..
        /// </summary>
        public static string Requests_Paragraph {
            get {
                return ResourceManager.GetString("Requests_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string Requests_ReleaseDate {
            get {
                return ResourceManager.GetString("Requests_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no information available for the release date.
        /// </summary>
        public static string Requests_ReleaseDate_Unavailable {
            get {
                return ResourceManager.GetString("Requests_ReleaseDate_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By.
        /// </summary>
        public static string Requests_RequestedBy {
            get {
                return ResourceManager.GetString("Requests_RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Date.
        /// </summary>
        public static string Requests_RequestedDate {
            get {
                return ResourceManager.GetString("Requests_RequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons Requested.
        /// </summary>
        public static string Requests_SeasonsRequested {
            get {
                return ResourceManager.GetString("Requests_SeasonsRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests_Title {
            get {
                return ResourceManager.GetString("Requests_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Dropdown.
        /// </summary>
        public static string Requests_ToggleDropdown {
            get {
                return ResourceManager.GetString("Requests_ToggleDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string Requests_TvShowTabTitle {
            get {
                return ResourceManager.GetString("Requests_TvShowTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Search_Albums {
            get {
                return ResourceManager.GetString("Search_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Seasons.
        /// </summary>
        public static string Search_AllSeasons {
            get {
                return ResourceManager.GetString("Search_AllSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already in Plex!.
        /// </summary>
        public static string Search_AlreadyInPlex {
            get {
                return ResourceManager.GetString("Search_AlreadyInPlex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has already been requested!.
        /// </summary>
        public static string Search_AlreadyRequested {
            get {
                return ResourceManager.GetString("Search_AlreadyRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Search_Available {
            get {
                return ResourceManager.GetString("Search_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available on Plex.
        /// </summary>
        public static string Search_Available_on_plex {
            get {
                return ResourceManager.GetString("Search_Available_on_plex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string Search_ComingSoon {
            get {
                return ResourceManager.GetString("Search_ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong adding the movie to CouchPotato! Please check your settings..
        /// </summary>
        public static string Search_CouchPotatoError {
            get {
                return ResourceManager.GetString("Search_CouchPotatoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not check if {0} is in Plex, are you sure it&apos;s correctly setup?.
        /// </summary>
        public static string Search_CouldNotCheckPlex {
            get {
                return ResourceManager.GetString("Search_CouldNotCheckPlex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Search_Country {
            get {
                return ResourceManager.GetString("Search_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but your administrator has not yet enabled this functionality..
        /// </summary>
        public static string Search_ErrorNotEnabled {
            get {
                return ResourceManager.GetString("Search_ErrorNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but this functionality is currently only for users with Plex accounts.
        /// </summary>
        public static string Search_ErrorPlexAccountOnly {
            get {
                return ResourceManager.GetString("Search_ErrorPlexAccountOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Season.
        /// </summary>
        public static string Search_FirstSeason {
            get {
                return ResourceManager.GetString("Search_FirstSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Theaters.
        /// </summary>
        public static string Search_InTheaters {
            get {
                return ResourceManager.GetString("Search_InTheaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Season.
        /// </summary>
        public static string Search_LatestSeason {
            get {
                return ResourceManager.GetString("Search_LatestSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string Search_Modal_SeasonsTitle {
            get {
                return ResourceManager.GetString("Search_Modal_SeasonsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie status.
        /// </summary>
        public static string Search_Movie_Status {
            get {
                return ResourceManager.GetString("Search_Movie_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Search_Movies {
            get {
                return ResourceManager.GetString("Search_Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find the artist on MusicBrainz. Please try again later or contact your admin.
        /// </summary>
        public static string Search_MusicBrainzError {
            get {
                return ResourceManager.GetString("Search_MusicBrainzError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Requested yet.
        /// </summary>
        public static string Search_Not_Requested_Yet {
            get {
                return ResourceManager.GetString("Search_Not_Requested_Yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not remove this notification because you never had it!.
        /// </summary>
        public static string Search_NotificationError {
            get {
                return ResourceManager.GetString("Search_NotificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to watch something that is not currently on Plex?! No problem! Just search for it below and request it!.
        /// </summary>
        public static string Search_Paragraph {
            get {
                return ResourceManager.GetString("Search_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending approval.
        /// </summary>
        public static string Search_Pending_approval {
            get {
                return ResourceManager.GetString("Search_Pending_approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing request.
        /// </summary>
        public static string Search_Processing_Request {
            get {
                return ResourceManager.GetString("Search_Processing_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string Search_ReportIssue {
            get {
                return ResourceManager.GetString("Search_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Search_Request {
            get {
                return ResourceManager.GetString("Search_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request denied.
        /// </summary>
        public static string Search_Request_denied {
            get {
                return ResourceManager.GetString("Search_Request_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        public static string Search_Requested {
            get {
                return ResourceManager.GetString("Search_Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Search_Season {
            get {
                return ResourceManager.GetString("Search_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Episode.
        /// </summary>
        public static string Search_SelectEpisode {
            get {
                return ResourceManager.GetString("Search_SelectEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Season.
        /// </summary>
        public static string Search_SelectSeason {
            get {
                return ResourceManager.GetString("Search_SelectSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me a notification when items I have requested have been added.
        /// </summary>
        public static string Search_SendNotificationText {
            get {
                return ResourceManager.GetString("Search_SendNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong adding the movie to SickRage! Please check your settings..
        /// </summary>
        public static string Search_SickrageError {
            get {
                return ResourceManager.GetString("Search_SickrageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was successfully added!.
        /// </summary>
        public static string Search_SuccessfullyAdded {
            get {
                return ResourceManager.GetString("Search_SuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string Search_Suggestions {
            get {
                return ResourceManager.GetString("Search_Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Count.
        /// </summary>
        public static string Search_TrackCount {
            get {
                return ResourceManager.GetString("Search_TrackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV show status.
        /// </summary>
        public static string Search_TV_Show_Status {
            get {
                return ResourceManager.GetString("Search_TV_Show_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request of TV Shows is not correctly set up. Please contact your admin..
        /// </summary>
        public static string Search_TvNotSetUp {
            get {
                return ResourceManager.GetString("Search_TvNotSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string Search_TvShows {
            get {
                return ResourceManager.GetString("Search_TvShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View In Plex.
        /// </summary>
        public static string Search_ViewInPlex {
            get {
                return ResourceManager.GetString("Search_ViewInPlex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached your weekly request limit for Albums! Please contact your admin..
        /// </summary>
        public static string Search_WeeklyRequestLimitAlbums {
            get {
                return ResourceManager.GetString("Search_WeeklyRequestLimitAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached your weekly request limit for Movies! Please contact your admin..
        /// </summary>
        public static string Search_WeeklyRequestLimitMovie {
            get {
                return ResourceManager.GetString("Search_WeeklyRequestLimitMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached your weekly request limit for TV Shows! Please contact your admin..
        /// </summary>
        public static string Search_WeeklyRequestLimitTVShow {
            get {
                return ResourceManager.GetString("Search_WeeklyRequestLimitTVShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are an administrator, please use the other login page.
        /// </summary>
        public static string UserLogin_AdminUsePassword {
            get {
                return ResourceManager.GetString("UserLogin_AdminUsePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect User or Password.
        /// </summary>
        public static string UserLogin_IncorrectUserPass {
            get {
                return ResourceManager.GetString("UserLogin_IncorrectUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to watch a movie or tv show but it&apos;s not currently on Plex?
        ///            Login below with your Plex.tv username and password!.
        /// </summary>
        public static string UserLogin_Paragraph {
            get {
                return ResourceManager.GetString("UserLogin_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login details are only used to authenticate your Plex account..
        /// </summary>
        public static string UserLogin_Paragraph_SpanHover {
            get {
                return ResourceManager.GetString("UserLogin_Paragraph_SpanHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserLogin_Password {
            get {
                return ResourceManager.GetString("UserLogin_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string UserLogin_SignIn {
            get {
                return ResourceManager.GetString("UserLogin_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UserLogin_Title {
            get {
                return ResourceManager.GetString("UserLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plex.tv Username .
        /// </summary>
        public static string UserLogin_Username {
            get {
                return ResourceManager.GetString("UserLogin_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserLogin_Username_Placeholder {
            get {
                return ResourceManager.GetString("UserLogin_Username_Placeholder", resourceCulture);
            }
        }
    }
}
