name: Automation Tests

on:
  push:
    branches: [ develop, feature/** ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  automation-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - uses: actions/cache@v4
      with:
        path: |
          '**/node_modules'
          '/home/runner/.cache/Cypress'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install Frontend Deps
      run: yarn --cwd ./src/Ombi/ClientApp install

    - name: Install Test Dependencies
      run: yarn --cwd ./tests install

    - name: Start Frontend
      run: |
        nohup yarn --cwd ./src/Ombi/ClientApp start &

    - name: Restore .NET Dependencies
      run: dotnet restore ./src/Ombi/Ombi.csproj

    - name: Build .NET Project
      run: dotnet build ./src/Ombi/Ombi.csproj --no-restore

    - name: Start Backend
      run: |
        nohup dotnet run --project ./src/Ombi -- --host http://*:3577 &

    - name: Run Wiremock
      run: nohup docker run --rm -p 32400:8080 --name wiremock wiremock/wiremock:2.35.0 &

    - name: Sleep for server to start
      run: sleep 20

    - name: Cypress Tests
      uses: cypress-io/github-action@v4
      with:
        record: true
        browser: chrome
        headless: true
        working-directory: tests
        wait-on: http://localhost:3577/
        # 10 minutes
        wait-on-timeout: 600
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Stop Services
      if: always()
      run: |
        pkill -f "dotnet.*Ombi" || true
        docker container kill wiremock || true