name: 'Chromatic'

# Event for the workflow
on:
  push:
  workflow_dispatch:

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Ombi/ClientApp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: NodeModules Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Publish to Chromatic
        if: github.ref != 'refs/heads/master'
        uses: chromaui/action@v1
        with:
          projectToken: 7c47e1a1a4bd
          exitZeroOnChanges: true

      - name: Publish to Chromatic and auto accept changes
        if: github.ref == 'refs/heads/master'
        uses: chromaui/action@v1
        with:
          projectToken: 7c47e1a1a4bd
          autoAcceptChanges: true # 👈 Option to accept all changes
